codeceptjs/ui

src/components/Header.vue
src/components/pages/ScenariosPage.vue

make top nav responsive

---

src/components/CapabilityFolder.vue
src/components/Console.vue
src/components/Feature.vue
src/components/pages/ScenariosPage.vue

(feat):Add the ability to toggle the test scenarios for a clean UI

---

src/components/Console.vue

Fix: in label show icons

---

package.json

Fixes this https://github.com/codecept-js/ui/issues/24

(fix):serve backend with examples

---

src/components/CapabilityFolder.vue
src/components/Feature.vue
src/components/pages/ScenariosPage.vue

Revert "(feat):Add the ability to toggle the test scenarios for a clean UI"

---

lib/api/open-test-in-editor.js
lib/model/open-in-editor.js
lib/utils/mkdir.js
package-lock.json
src/App.vue
src/components/ScenarioSource.vue
src/components/pages/TestRunPage.vue

Fix: error message init

---

lib/model/codeceptjs-factory.js
src/components/EditorNotFound.vue
src/components/Feature.vue
src/components/ScenarioSource.vue
src/components/Step.vue

Moved modal window with error to standalone component

Added better description for error on editor

---

README.md
package.json

A good way to encourage contributors is showing their faces on readme file. They would feel somehow a bit proud of what they are contributing. 😊 And that encourages others to be shown on the list as well.

generate the contributors list

---

src/components/pages/TestRunPage.vue

This PR aims to fix https://github.com/codecept-js/ui/issues/44

fix overlapped no editor popup

---

package.json
vue.config.js

Hi, I have a problem to start this project on windows
Use node to launch file JS in cmd `backend` and `examples`

:bug: Fix command backend and example on windows

---

package-lock.json
package.json

fixes: #55 
- Updated Codeceptjs and Puppeteer to latest stable version.

[fix] Session Closing On Test Run

---

src/components/Pause.vue

[Feat] Enhance Interactive Pause UI

---

lib/api/list-actions.js
src/components/Pause.vue

[Feat] Implement UI Action Documentation (Interactive Pause)

---

src/components/Pause.vue

Add documentation as part of list-action API along with Commands and Params
Closes: #59

[Feat] Add Documentation In List Actions Api

---

lib/model/snapshot-store/fix-html-snapshot.js

Because it throws error in tests

Fixed extractUrlWithPath() in tests

---

README.md
bin/codecept-ui.js
lib/api/list-steps.js
lib/app.js
lib/codeceptjs/brk.js
lib/commands/init.js
lib/config/env.js
lib/config/url.js
lib/model/ws-events.js
lib/utils/mkdir.js
lib/utils/port-type-validator.js
lib/utils/port-validator.js
package.json
src/main.js
vue.config.js

Protocol | Default port
--- | ---
ws:// | 2999
http:// | 3333

Added --port and --wsPort configuration options to codecept-ui

---

lib/codeceptjs/realtime-reporter.helper.js

fix "helper is required" error when using Protractor

---

README.md
lib/api/index.js
src/main.js

Removed useless WS_PORT hardcode from Vue application.
Resolves #80

Added dynamic ws:// port definition through server request

---

lib/api/get-page-objects.js
lib/api/index.js
lib/utils/absolutize-paths.js

Resolves #81 
Returns 
```
{
pageObject: { path, source, methods },
}
```

Added endpoint for extracting collection of page objects and their methods

---

lib/api/get-steps.js
lib/api/index.js

Returns 
```
{
"name": {
"file",
"line",
"column",
}
}
```
Resolves #84

Added endpoint for extracting BDD steps

---

README.md
package-lock.json
src/components/RunButton.vue
src/components/SettingsMenu.vue
src/components/pages/ScenariosPage.vue

settings menu-item is now displayed on mobile version, adjusted therefore few components and made them more "mobile-responsive".
Several menu items can now also be added.

Menu Adjustments

---

src/components/Test.vue

fix issue https://github.com/codeceptjs/ui/issues/109

fix step tabs

---

README.md
package.json
src/components/Logo.vue

fix issue https://github.com/codeceptjs/ui/issues/128

update relative repo
